version: 2
jobs:
  build-frontend:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/project/cluster/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - frontend-node_modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: ./use_cache_or_npm_install.sh
      - run: echo $FIREBASE_CONFIG > ~/project/cluster/credentials/firebaseConfig.js
      - run:
          command: ./build.sh ${CIRCLE_BRANCH}
      - save_cache:
          key: frontend-node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - '~/project/cluster/frontend/node_modules'
      - save_cache:
          key: frontend-dist-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - '~/project/cluster/frontend/dist'
  build-agent:
    machine: true
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: docker build -t gcr.io/${GOOGLE_PROJECT_ID}/agent -f ./cluster/agent/Dockerfile .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gcloud docker -- push gcr.io/${GOOGLE_PROJECT_ID}/agent
  build-data-job-runner:
    machine: true
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: docker build -t gcr.io/${GOOGLE_PROJECT_ID}/data-job-runner -f ./cluster/data-job-runner/Dockerfile .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gcloud docker -- push gcr.io/${GOOGLE_PROJECT_ID}/data-job-runner
  build-functions:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/project/cluster/functions
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - functions-node_modules-{{ .Branch }}-{{ checksum "package.json"}}
      - run:
          command: ./use_cache_or_npm_install.sh
      - run:
          command: ./build.sh
      - save_cache:
          key: functions-node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - '~/project/cluster/functions/node_modules'
      - save_cache:
          key: functions-dist-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - '~/project/cluster/functions/dist'
  build-server:
    machine: true
    working_directory: ~/project/cluster/server
    steps:
      - checkout:
          path: ~/project
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: docker build --rm=false -t gcr.io/${GOOGLE_PROJECT_ID}/nst-server:${CIRCLE_SHA1}${CIRCLE_BRANCH} .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gcloud docker -- push gcr.io/${GOOGLE_PROJECT_ID}/nst-server:${CIRCLE_SHA1}${CIRCLE_BRANCH}
  run-tests:
    resource_class: large
    machine: true
    working_directory: ~/project/cluster/integration-tests/
    steps:
      - checkout:
          path: ~/project
      - run:
          command: echo 'export NSTRUMENTA_API_KEY="${NSTRUMENTA_INTEGRATION_TEST_API_KEY}"' >> "$BASH_ENV"
      - run: ./ci.sh cli

workflows:
  version: 2

  -ci:
    jobs:
      - build-frontend
      - build-server
      - build-agent
      - build-data-job-runner
      - build-functions
      - run-tests
